# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Lưu trữ dữ liệu vật lý

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data:
  redis_data: